Add customer deserializers
Pylons/pyramid_openapi3 pull request #151
Opened 2021-08-14 20:34 UTC by daryllstrauss

Openapi-core supports custom deserializers which converts mimetypes other than json into objects that can then be validated.

This patch allows developers to call config.pyramid_openapi3_add_deserializer and add additional deserializers. It is modeled after customer_formatters

2021-08-14 20:54 UTC, daryllstrauss commented
This is failing in the "black" tests because of a Makefile problem running lint.
I don't think that's from my changes, but if it is let me know what I can do.

2021-08-15 05:39 UTC, zupo requested changes
The code itself is OK, but it needs more exhaustive tests, mainly to show how to use this feature. The custom formatters feature has a  suite of tests that showcase how custom formatters can be used. Custom deserializers should have the same.

https://github.com/Pylons/pyramid_openapi3/blob/2e455cb2d523a58d3d6111354ed5406c0d442183/pyramid_openapi3/tests/test_extract_errors.py#L566

2021-08-15 05:40 UTC, zupo commented on pyramid_openapi3/__init__.py
> +                custom_media_type_deserializers=custom_deserializers
```suggestion
                custom_media_type_deserializers=custom_deserializers,
```

2021-08-15 05:40 UTC, zupo commented on pyramid_openapi3/__init__.py
> +                custom_media_type_deserializers=custom_deserializers
```suggestion
                custom_media_type_deserializers=custom_deserializers,
```

2021-08-15 05:40 UTC, zupo commented on pyramid_openapi3/__init__.py
> +                custom_media_type_deserializers=custom_deserializers
```suggestion
                custom_media_type_deserializers=custom_deserializers,
```

2021-08-15 05:41 UTC, zupo commented on pyramid_openapi3/__init__.py
> +                custom_media_type_deserializers=custom_deserializers
```suggestion
                custom_media_type_deserializers=custom_deserializers,
```

2021-08-15 05:42 UTC, zupo commented on pyramid_openapi3/__init__.py
> +                custom_media_type_deserializers=custom_deserializers
I think this is what trips `black`. Please run `black <path_to_file>` or `pipenv run black <path_to_file>` locally to be sure.

2021-08-15 05:43 UTC, zupo commented
Good PR in general! Needs a bit of final polish, then I can merge it.

2021-08-17 06:28 UTC, merged

2021-08-17 06:28 UTC, zupo commented
Thanks!